#!/usr/bin/env bash
# Auto-generated by agent-indicator. Do not edit.
# original-notify: ["bash", "/Users/accessd/.tmux/plugins/tmux-agent-indicator/adapters/codex-notify.sh"]
set -uo pipefail
"bash" "/Users/accessd/.tmux/plugins/tmux-agent-indicator/adapters/codex-notify.sh" "$@" 2>/dev/null || true
exec "/Users/accessd/projects/github/accessd/agent-indicator/adapters/codex-notify.sh" "$@"
